# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 569da01266f694006f33a6687d2f3058b8cee941c7cf72187b180c2c60e3e079cb453c98490a4fd32359c6dd2dff9e4bd290a0113b30e9d73e6021b73932ffe3

test:
  secret_key_base: 880fd9a873a61ae8093dbb59b942281e60c2bcec71fca81684c379ea16f0b9c2b125d787c3e164f269d5aea936c4341c1e968d317d67678d9f7490f3beb85ec1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
